### ISSUE TITLE
Support of prefix for build.gradle.kts

### ISSUE THREAD

**Issue by bjonnh** [JetBrains/gradle-idea-ext-plugin#114]
I had to do that to start getting support for package prefix, could it be somehow included in the plugin?

````
fun org.gradle.plugins.ide.idea.model.IdeaModule.settings(configure: org.jetbrains.gradle.ext.ModuleSettings.() -> Unit) =
    (this as ExtensionAware).configure(configure)

val org.jetbrains.gradle.ext.ModuleSettings.packagePrefix: org.jetbrains.gradle.ext.PackagePrefixContainer
    get() = (this as ExtensionAware).the()

idea {
    module {
        settings {
            packagePrefix["src/main/kotlin"] = "net.nprod"
        }
    }
}
````

**Comment by bjonnh** [comment]
On a more general note, why don't we have a way to define easily that as the official Kotlin style guide says that omitting the root of packages is the favored style for pure Kotlin projects.

**Comment by ivan-klass** [comment]
👍  Also suffer from this.
I was trying to add these DSL extenstions into `buildSrc` but just adding

dependency (`"gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:0.10"`) into `buildSrc/build.gradle.kts`
makes project crash with repository errors. Adding with `compileOnly` causes runtime class not found error, even when plugin is applied

**Comment by ryantheleach** [comment]
IntellijJ docs impy this is fixed: https://www.jetbrains.com/help/idea/work-with-gradle-projects.html#package_prefixes

**Comment by nskvortsov** [comment]
@ryantheleach this issue is about providing necessary Kotlin bindings for the IDEA-Ext dsl. So it is still open
