### ISSUE TITLE
Support ArtifactManager

### ISSUE THREAD

**Issue by snrostov** [JetBrains/gradle-idea-ext-plugin#2]
Please add support for `ArtifactManager`. Use case is building Kotlin project using JPS. This elements is required for project:
- `directory`
- `archive`
- `module-output`
- `file-copy`
- `dir-copy`
- `library`
- `extracted-dir`.

Currently this is generated using external tool called `pill` based on gradle `copy` tasks definition: https://github.com/JetBrains/kotlin/blob/master/buildSrc/src/main/kotlin/pill/kotlinPluginArtifact.kt.

It would be super cool if this will be supported through "native" Idea Gradle Import.

**Comment by nskvortsov** [comment]
Needs:
 * dependencies configurations
 * projects production output
 * lazy resolution of paths
 * present as a copy spec for Gradle tasks

**Comment by nskvortsov** [comment]
implemented. The DSL is documented here https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/Artifacts-DSL

**Comment by henning-meinhardt** [comment]
Is it possible to define the type of artifact (e.g. "war" or "war exploded")?

**Comment by nskvortsov** [comment]
war and war exploded artifacts are created by native import based on Gradle's "war" plugin configuration.

**Comment by nskvortsov** [comment]
I see. Thank you for the follow-up. Indeed, artifact types are not supported in this DSL at the moment. And it deserves a report at JetBrains Youtrack: https://youtrack.jetbrains.com/newIssue?project=IDEA&summary=Gradle%20IDEA%20Ext&c=Subsystem%20Build.%20Gradle&c=tag%20idea_ext

What I wanted to say is that you can create additional tasks of type `WAR` that define you new artifact. Based on these, new war and exploded war artifacts should be created in IDEA.
