### ISSUE TITLE
Unable to set workingDirectory

### ISSUE THREAD

**Issue by deepy** [JetBrains/gradle-idea-ext-plugin#20]
I tried the following:

```
idea {
    project {
        settings {

            runConfigurations {
                "MyApp"(Application) {
                    mainClass = 'foo.App'
                    moduleName = "hi"
                    workingDirectory = "/home/alex"
                }
            }

            copyright { }
        }
    }
}
```

And I get the launcher, but my working directory is shown as `/home/alex/projects/testcase`

**Comment by deepy** [comment]
@nskvortsov any chance of getting this looked at?

I'm still getting this even with 0.4 and IJ 2018.2

This is the only thing preventing me from putting this into test

**Comment by nskvortsov** [comment]
Fixed in Idea
Should be delivered with 2018.2.2
