### ISSUE TITLE
Customize module type

### ISSUE THREAD

**Issue by jk1** [JetBrains/gradle-idea-ext-plugin#21]
I'd like to customize Intellij module type. Is it something, that's currently possible to achieve with the plugin?

**Comment by nskvortsov** [comment]
not at the moment. What exactly would you like to customize?

Most of the time, Intellij should be smart enough to pick up module type by itself.

**Comment by nskvortsov** [comment]
Is this module type provided by stardust ide plugin?

ср, 27 июн. 2018 г., 16:25 jk1 <notifications@github.com>:

**Comment by jk1** [comment]
I believe so. @rayshade as a plugin author can comment more on that.

**Comment by nskvortsov** [comment]
I guess, plugin could provide such customization with corresponding support from Idea 2018.3

**Comment by nskvortsov** [comment]
also requested by https://github.com/gradle/gradle/issues/10162

**Comment by nskvortsov** [comment]
corresponding IDEA ticket: https://youtrack.jetbrains.com/issue/IDEA-239748

**Comment by nskvortsov** [comment]
Implemented plugin code.
IDEA support is pending and planned in 2020.3 (see IDEA ticked above)

**Comment by jk1** [comment]
Thanks for implementing it. Can't wait to try it out.

**Comment by baron1405** [comment]
Where is this documented?

**Comment by baron1405** [comment]
FWIW I verified that add:
```
idea {
    module {
        settings {
            rootModuleType = 'PYTHON_MODULE'
        }
    }
}
```
to the build.gradle of a Python subproject results in its module being marked as a Python module.
