### ISSUE TITLE
Customising .iml files location

### ISSUE THREAD

**Issue by Takhion** [JetBrains/gradle-idea-ext-plugin#23]
We want our `.iml` files to live under `.idea/modules`, but right now that doesn't seem possible to achieve through the plugin, am I correct @nskvortsov?

**Comment by nskvortsov** [comment]
@Takhion what IDEA version are you using?

**Comment by Takhion** [comment]
@nskvortsov `2018.1.6`

**Comment by nskvortsov** [comment]
Management of *.iml files location will stay out of scope of this plugin. Try Idea 2018.2, AFAIK, it should store modules under `.idea/modules` by default.
