### ISSUE TITLE
An ability to configure default encoding

### ISSUE THREAD

**Issue by dtsaryov** [JetBrains/gradle-idea-ext-plugin#29]
There is a couple of settings that configures which charset should be used:

![ij_idea_encoding](https://user-images.githubusercontent.com/6183810/43701087-0699ed4c-9966-11e8-9dac-a59bc9541b03.png)

But the plugin doesn't provide an ability that enables to configure these encoding settings at the moment.

**Comment by dtsaryov** [comment]
hi @nskvortsov

any chances for this issue to be implemented soon?

**Comment by nskvortsov** [comment]
I will see if I can include this to 2018.3

**Comment by dtsaryov** [comment]
@nskvortsov 
Does it require so many changes that prevent including it into 2018.2?

**Comment by nskvortsov** [comment]
to begin with, the  implementation is not that straight forward, as multiple Gradle projects can be imported in one idea project

**Comment by nskvortsov** [comment]
implemented by @DeveloperHacker  in 64d30d9c9a818648cef5480b19b300a1c347937c
will require 2019.1
