### ISSUE TITLE
Allow specifying "Shorten command line" on run configurations

### ISSUE THREAD

**Issue by trejkaz** [JetBrains/gradle-idea-ext-plugin#32]
On run configs of all types, it would be nice if we could set "Shorten command line" from the Gradle build.

At present, Windows developers have to set this manually after the project is imported, or all run configs fail for them.

**Comment by lptr** [comment]
This would be useful for us, too.

**Comment by nskvortsov** [comment]
added following syntax to application, testNG and Junit run configurations:
    
    import static org.jetbrains.gradle.ext.ShortenCommandLine.*
    ...
    shortenCommandLine = MANIFEST`

Will be available in v0.5 + Idea 2018.3
