### ISSUE TITLE
Support an ability to enable delegating build/run actions to Gradle

### ISSUE THREAD

**Issue by dtsaryov** [JetBrains/gradle-idea-ext-plugin#4]
Intellij IDEA has an ability to delegate IDE build/run actions to Gradle (`Build, Execution, Deployment` -> `Build Tool`s -> `Gradle` -> `Runner`).

It will be great to be able to configure this setting.

**Comment by nskvortsov** [comment]
proposed syntax

    import org.jetbrains.gradle.ext.*
    import static org.jetbrains.gradle.ext.ActionDelegationConfig.TestRunner.*
    
    idea {
      project.settings {
        delegateActions {
          delegateBuildRunToGradle = true
          testRunner = CHOOSE_PER_TEST
        }
      }
    }

**Comment by E3V3A** [comment]
I never understood what this setting does. 
Can someone please explain?
