### ISSUE TITLE
How to apply the plugin to a multi-project build?

### ISSUE THREAD

**Issue by jk1** [JetBrains/gradle-idea-ext-plugin#42]
I don't like Idea detecting web facet from the build, so I'm trying to get rid of it with the plugin.
Here's the trivial build I'm doing my tests on: https://github.com/jk1/idea-ext-plugin-test

 1. I have tried to apply the plugin to the root project
 2. In idea removed web facet and artifacts
 3. Run gradle sync from Idea
 4. Facet and artifacts reappeared

Also tried to  apply the plugin to the web subproject directly. Upon gradle project refresh it just fails with an exception.

So, what's the proper way of going it?

**Comment by nskvortsov** [comment]
* you can apply plugin to the root project and provide configuration in any subprojects you need
* plugin does not disable Idea's built-in web resources detection. Would you mind opening an issue in Idea tracker, that describes what's wrong with the Idea's detection of web facet?

**Comment by jk1** [comment]
Thanks for looking into it. 

> plugin does not disable Idea's built-in web resources detection

Just curios, what `doNotDetectFrameworks("web")`  does then?

> Would you mind opening an issue in Idea tracker, that describes what's wrong with the Idea's detection of web facet?

None of the issues I reported to Idea before has been replied or undated in any way. So I'm not sure if it makes any sense.

**Comment by nskvortsov** [comment]
> Just curios, what doNotDetectFrameworks("web") does then?
It is the DSL equivalent of "exclude facet from auto detection" https://www.jetbrains.com/help/idea/2018.3/creating-and-managing-modules.html#add-support-for-frameworks-technologies

**Comment by jk1** [comment]
This should work for me. With web facet excluded from autodetection there should be neither "web" facet, nor artifacts. Apparently it doesn't work in the test project; facet still appears.

**Comment by nskvortsov** [comment]
The Gradle import is independent of facets autodetection, and does own job
of setting up web artifacts.

чт, 20 сент. 2018 г. в 18:44, jk1 <notifications@github.com>:

**Comment by jk1** [comment]
I see, thanks. I appreciate you looking into this.
