### ISSUE TITLE
afterSync task does not get triggered

### ISSUE THREAD

**Issue by trejkaz** [JetBrains/gradle-idea-ext-plugin#43]
I'm running IDEA 2018.2.4. In our build, we have:

```
gradle.taskGraph.whenReady {
  idea.project.settings.taskTriggers {
    afterSync project(':some-subproject').tasks.getByName('generateGrammarSource')
  }
}
```

But after syncing the Gradle project, the task does not get run.

The example on the Wiki doesn't include the `gradle.taskGraph.whenReady` fragment, but it turns out that if you don't do that, the task doesn't exist yet, so you can't reference it. So we wait until all tasks are loaded before setting the property, but setting the property itself doesn't appear to work.

**Comment by guylabs** [comment]
I had similar issues and I could never properly verify it as the task triggers weren't shown in the Gradle tab. See #37 for details.

**Comment by trejkaz** [comment]
I'm able to verify that the task hasn't run, because our task generates source code from ANTLR grammars, and compiling the code fails if it hasn't been generated.

**Comment by nskvortsov** [comment]
@trejkaz task graph is never created during import, so your configuration is never actually applied. 
How (and when) do you create the task?
Did you try to change `taskGraph.whenReady` to `project.afterEvaluate` ?

**Comment by nskvortsov** [comment]
please, try this:
    
    project(':some-subproject').afterEvaluate {
      rootProject.idea.project.settings.taskTriggers {
        afterSync project(':some-subproject').tasks.getByName('generateGrammarSource')
      }
    }

**Comment by trejkaz** [comment]
If I do this:

```
project(':storage-core').afterEvaluate {
  rootProject.idea.project.settings.taskTriggers {
    def task = project(':storage-core').tasks.getByName('generateGrammarSource')
    System.err.println("About to add to afterSync: ${task}")
    afterSync task
  }
}
```

I see the output saying that the task is not null, but IDEA still doesn't execute the task.

**Comment by trejkaz** [comment]
Well, turns out I can manually add the task as an After Sync task, through the UI. So it really just seems that afterSync in the API has no effect.

**Comment by GFriedrich** [comment]
Mh seems that this feature broke with one of the newer 2018.2.X releases. I remember that it worked with at least 2018.2 and 2018.2.1 but with the latest 2018.2.5 it's also not working for me anylonger.

**Comment by trejkaz** [comment]
If it used to work in an earlier IDEA and broke later, should I be filing it against IDEA itself, instead of here, perhaps?

**Comment by nskvortsov** [comment]
@trejkaz is this still an issues in 2018.3 ?
There is a cosmetics issue with Build Tool Output window not displayed and task not marked in the UI, but the task itself get executed. Can you confirm?

**Comment by guylabs** [comment]
@nskvortsov it works for us on `2018.3` but its still not shown in the UI that the task has a trigger active.

**Comment by nskvortsov** [comment]
thanks @guylabs , will fix task activation hint soon.

**Comment by trejkaz** [comment]
Tried this now on 2018.3:

* Fresh clone of the repo
* Open in IDEA
* Import Gradle Project
* Output looks like this:

        > Task :buildSrc:compileJava
        > Task :buildSrc:compileGroovy NO-SOURCE
        > Task :buildSrc:processResources NO-SOURCE
        > Task :buildSrc:classes
        > Task :buildSrc:jar
        > Task :buildSrc:assemble
        > Task :buildSrc:compileTestJava NO-SOURCE
        > Task :buildSrc:compileTestGroovy NO-SOURCE
        > Task :buildSrc:processTestResources NO-SOURCE
        > Task :buildSrc:testClasses UP-TO-DATE
        > Task :buildSrc:test NO-SOURCE
        > Task :buildSrc:check UP-TO-DATE
        > Task :buildSrc:build

        > Configure project :
        [buildinfo] Not using buildInfo properties file for this build.
        The IvyArtifactRepository.layout(String, Closure) method has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the IvyArtifactRepository.patternLayout(Action) method instead.

        CONFIGURE SUCCESSFUL in 35s

        CONFIGURE SUCCESSFUL in 0s

* I don't see anything about it running the task in the output. The source files I expected the task to create haven't been created either.
* If I manually refresh from Gradle again, I get the same result.

I added diagnostics:

    project(':storage-core') {
      afterEvaluate {
        rootProject.idea.project.settings.taskTriggers {
          println("adding: ${tasks.getByName('generateGrammarSource')}")
          afterSync tasks.getByName('generateGrammarSource')
        }
      }
    }

The `println` there _does_ appear in the output, so I know it's adding it - it just isn't getting run.

**Comment by trejkaz** [comment]
Simpler check:

    task('testIdea') {
      doLast {
        println('I\'m being run!')
      }
    }

    idea.project.settings.taskTriggers {
      println("Being added: ${tasks.getByName('testIdea')}")
      afterSync tasks.getByName('testIdea')
    }

I get the "Being added" line output, but not the "I'm being run!" line.

**Comment by trejkaz** [comment]
Demo project: https://github.com/trejkaz/idea-ext-issue-43

**Comment by nskvortsov** [comment]
@trejkaz thank you for the sample project!
Indeed, there is an issue with tool window not being open for a trigger-activated task, so calling `println` inside `doFirst` do not show up.
As a check, can I suggest using something like

    task('testIdea') {
      doFirst {
        new File(project.rootDirectory,'test.txt').write(System.currentTimeMillis())
      }
    }

**Comment by nskvortsov** [comment]
@trejkaz  I've created a pull request for your project https://github.com/trejkaz/idea-ext-issue-43/pull/1

Unfortunately, task failure is hidden and this should get fixed on IDEA side.

**Comment by trejkaz** [comment]
With the change in that PR, it seems to behave the same. In "Build: Sync" window:

```
> Configure project :
Being added: task ':testIdea'

CONFIGURE SUCCESSFUL in 0s
```

But the file does not appear.

The task works fine from the command-line:

```
$ cat testIdea.log
cat: testIdea.log: No such file or directory
$ ./gradlew testIdea

> Configure project :
Being added: task ':testIdea'

> Task :testIdea
I'm being run!

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
$ cat testIdea.log
Task was run
```

I went to the Gradle tool window to see whether the task would run from there, but it seems to be missing from there entirely, so I don't know what's going on there.

In the full project, the task does appear in the Gradle tool window, and the task does run when I run it manually, but does not get run when the project is imported. So neither work, but now there are two different bugs going on? :/

**Comment by Mobe91** [comment]
This works for me using IDEA 2019.3.4 so I guess the issue can be closed?

**Comment by nskvortsov** [comment]
@trejkaz  getting back to this: is does `afterSycn` work for you ATM ?

**Comment by trejkaz** [comment]
Currently using: IDEA 2020.2.2

Steps:

* Clone https://github.com/trejkaz/idea-ext-issue-43
* Open in IDEA
* Wait for it to import


Results: task is not run, build dir is not created and no errors come out either. When I refresh, I do see:

"Being added: task ':testIdea'"

So it definitely knows about the test, but I see no evidence of it being run.

**Comment by trejkaz** [comment]
Oh right, that was still with v0.2.

Updated build.gradle to get gradle-idea-ext:0.7 instead, and now it does work. So I guess we're good to close this.

**Comment by nskvortsov** [comment]
Thank you for the followup!
