### ISSUE TITLE
Use absolute task name for task triggers instead of Task instance

### ISSUE THREAD

**Issue by guylabs** [JetBrains/gradle-idea-ext-plugin#45]
Currently the task triggers 
https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/Change-log-DSL-v0.2#gradle-tasks-triggers-settings are defined by passing a `Task` instance. Changing that to be an absolute task name as `String` simplifies the configuration of these task triggers.

Instead of
```
    idea.project.settings.taskTriggers {
        afterSync tasks.getByName('afterSyncTask')
    }
```
it should be 
```
    idea.project.settings.taskTriggers {
        afterSync ':afterSyncTask'
    }
```

**Comment by wolfs** [comment]
👍 Using actual task instances also requires to realize those tasks on every build. Especially when using [task configuration avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) this requires task to be realized on every build.

**Comment by eskatos** [comment]
👍 to accept task paths

Accepting `TaskProvider<T>` would also be nice to prevent realizing tasks when not needed.

**Comment by trejkaz** [comment]
This approach works around some of the shortcoming:

    // ESOTERICA: Calling this `ideaDependencies` doesn't work because IDEA
    // hides the task from view for some reason.
    def ideDependencies = tasks.register('ideDependencies') {
      group 'ide'
      description 'Builds anything required for IDEA to use the project correctly'
      dependsOn ':subproject1:task1'
      dependsOn ':subproject2:task2'
    }

    idea.project.settings.taskTriggers {
      afterSync ideDependencies.get()
    }

The eager call to `get()` means that you don't get configuration avoidance, but it at least lets us use the standard syntax when specifying the dependencies.

(IDEA still doesn't actually trigger the task automatically but that is a separate issue which I have not found a workaround for yet.)

**Comment by mkobit** [comment]
I didn't see this issue when I filled a similar issue at https://github.com/JetBrains/gradle-idea-ext-plugin/issues/71
