### ISSUE TITLE
Support Gradle Run Configurations

### ISSUE THREAD

**Issue by breandan** [JetBrains/gradle-idea-ext-plugin#47]
The `GradleTask` endpoint is defined inside `Application` calling the specified Gradle task before launch. It would be nice to support creating Gradle run configurations directly.

**Comment by nskvortsov** [comment]
Since the v0.1 you can create Gradle Run configurations using following syntax:

    idea.project.settings {
      runConfigurations {
        "Gradle run configuration name"(Gradle) {
          task = project.tasks["check"]
         }
       }
    }

**Comment by esword** [comment]
Now that Intellij 2019.2 is out,  will a new version of this plugin be cut with this feature?

**Comment by breandan** [comment]
It looks like this feature was (partially?) implemented -- if so, can the version published on the [Gradle Plugin Repository](https://plugins.gradle.org/plugin/org.jetbrains.gradle.plugin.idea-ext) be updated?
