### ISSUE TITLE
Artifacts DSL example doesn't work

### ISSUE THREAD

**Issue by BenLeggiero** [JetBrains/gradle-idea-ext-plugin#48]
The [Artifacts DSL example in the wiki](https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/Artifacts-DSL) doesn't work; it gives me this error:

```
Could not find method settings() for arguments [build_4z8uydoahxkv32xgrlo47x8ut$_run_closure6@6e62c97c] on object of type org.gradle.plugins.ide.idea.model.IdeaProject.
```

**Comment by nskvortsov** [comment]
What version of idea are you using?
Could you, please, share the build script content for investigation?

**Comment by BenLeggiero** [comment]
[Build script is here](https://github.com/BlueHuskyStudios/Blue-Base/blob/buildSystem/CircleCI/Archiving-Artifacts/build.gradle).


IntelliJ IDEA 2018.2.5 (Community Edition)
Build #IC-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by nskvortsov** [comment]
Thank you.
You need a EAP  build of 2018.3 for artifacts to work. Please, give it a try

**Comment by bkolb** [comment]
and the wrong plugin was applied

**Comment by BenLeggiero** [comment]
I abandoned this project shortly after filing this report. I'm sorry I neglected to return here to close it sooner
