### ISSUE TITLE
Kotlin DSL - Unresolved reference: settings

### ISSUE THREAD

**Issue by fraquack** [JetBrains/gradle-idea-ext-plugin#49]
What's the right syntax to apply settings with Kotlin DSL?
I tried this, but `settings` is not resolved:
```
idea {
    project{
        settings{
        }
    }
}
```

**Comment by nskvortsov** [comment]
indeed, duplicates #44

**Comment by jimklimov** [comment]
FWIW, a functional workaround is posted in #114 (checked with IDEA 2023.1.2 CE, plugin 1.1.7)
