### ISSUE TITLE
Cannot invoke method settings() on null object

### ISSUE THREAD

**Issue by sschuberth** [JetBrains/gradle-idea-ext-plugin#50]
In a Kotlin project, I'm trying out the [example](https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/Change-log-DSL-v0.2#gradle-tasks-triggers-settings) with IntelliJ 2018.3, but on Gradle sync I'm getting `Cannot invoke method settings() on null object`. Any idea any `idea.project` is `null`? I also tried wrapping it in `afterEvaluate` without any luck.

**Comment by sschuberth** [comment]
Nevermind, the issue was that I was applying the plugin in the sub-project where I needed the task to be run. After applying the plugin in the root project and doing only the `afterSync` in the sub-project everything works.

**Comment by dirkniblick** [comment]
FYI, I found a workaround. This will configure subprojects in a multi-project setup to use Intellij as the test runner instead of Gradle.
```
if(idea.project) {
	idea.project.settings {
		delegateActions {
			delegateBuildRunToGradle = true
			testRunner = org.jetbrains.gradle.ext.ActionDelegationConfig.TestRunner.PLATFORM
		}
	}
}
```
