### ISSUE TITLE
import in idea ignores sourceDirs and testSourceDirs

### ISSUE THREAD

**Issue by bkolb** [JetBrains/gradle-idea-ext-plugin#55]
I have a gradle file containing the following config:
```
allprojects {
   plugins.withType(YarnPlugin) {
        idea.module {
            excludeDirs += file("node_modules")

            sourceDirs += file("src")
            testSourceDirs += file("tests")

            iml.withXml {
                def node = it.asNode()
                node.@type = "WEB_MODULE"
            }
        }
    }
}
```

The YarnPlugin is a custom plugin similar to the gradle node plugin

If I run `./gradlew idea` on the cmd line and open the project, the source and test folders are mapped correctly. If I then run the gradle import from within Idea, all those mappings are gone again and the folders are just regular folders again. In combination with the fact, that the runConfigurations can only be created by the gradle import in idea (#54) this is currently a major problem for us when developing in a full stack project with idea ultimate.

**Comment by nskvortsov** [comment]
This report belongs to IDEA issue tracker. Please report at https://youtrack.jetbrains.com/issues/IDEA
If possible, please attach sample project, this will help a lot!
