### ISSUE TITLE
Value is null for Multimodule project Gradle 4.7 / IDEA 2018.3

### ISSUE THREAD

**Issue by citizenkahn** [JetBrains/gradle-idea-ext-plugin#58]
I see `Value is null` in intellij when attempting to set `javacAdditionalOptions` for a gradle multimodule.  I've tried placing the config into the top level build.gradle and in the sub module gradle.  Both produce the same result.

Any ideas what I'm doing incorrectly?
Thanks
Peter

# Environment
- Gradle 4.7 (tested with 4.10.3, 5.1 as well with same results)
- IDEA 2018.3
- Plugin gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:0.5

# Build.gradle
```
buildscript {

    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }

    }

    dependencies {
        classpath "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:0.5"
    }
}

def allNonEmptyProjects() {
    return subprojects.findAll { it.file("build.gradle").exists() || it.file(it.name + ".gradle").exists() }
}

configure(allNonEmptyProjects()) {

    apply plugin: 'eclipse'
    apply plugin: 'java'
    apply plugin: 'maven'
    apply plugin: "org.jetbrains.gradle.plugin.idea-ext"

   idea {
        project {
            settings{
                compiler {
                    javac {
                        javacAdditionalOptions  "-parameters"
                    }
                }
            }
        }
    }
}

group 'myorg'
version '1.0-SNAPSHOT'

repositories {
    jcenter()
}

```

# Error

[failure.txt](https://github.com/JetBrains/gradle-idea-ext-plugin/files/2721326/failure.txt)

**Comment by citizenkahn** [comment]
Initially I had `compile` not `compiler` and I fixed that but continue to see the problem.

**Comment by citizenkahn** [comment]
`org.jetbrains.gradle.plugin.idea-ext` application and its DSL must happen in the root section and not applied per project.

**Comment by scicompth** [comment]
Is it possible to set this per module, some thing like below

    idea {
      project {
        settings{
          compiler {
            moduleName "moduleA"
            javac {
              javacAdditionalOptions  "-param"
            }
          }
        }
      }
    }

**Comment by nskvortsov** [comment]
@scicompth  please open separate feature request.

**Comment by tyresepoq** [comment]
I ran into a similar issue where I see `Value is null`. When I comment out the `idea` closure it works for me, but when I add `idea.project{ ... }` it causes the error. Is there a required field for this plugin that hasn't been set?

**Comment by jamesdh** [comment]
Can confirm that `IdeaProject` is broken when defined in a sub-module of a multi-module config. 

Simply commenting out the `project` closure gets things working again. Having a IdeaModule or IdeaWorkspace closure defined does not cause any breakages, however.
