### ISSUE TITLE
Is there a hook for running build tasks which are necessary to make IDEA work?

### ISSUE THREAD

**Issue by trejkaz** [JetBrains/gradle-idea-ext-plugin#6]
Any project which has generated sources, if imported directly into IDEA, isn't going to compile until someone manually runs the generateSources task.

Is there a way with this plugin to specify a series of tasks which must be run as part of the import process?

**Comment by nskvortsov** [comment]
In v0.1 you can generate `Gradle` run configuration with a task to generate sources and just run it after the import.

    runConfigurations {
        "generate_sources"(Gradle) {
            task = project(":my-project").tasks["generateSources"]
        }
    }

**Comment by jreznot** [comment]
But it still requires manual action from developer

**Comment by nskvortsov** [comment]
@jreznot if an auto-import is enabled, would you expect sources to be regenerated each time?

**Comment by jreznot** [comment]
As Gradle uses inputs / outputs cache it will not generate sources again if I do not change source files

**Comment by trejkaz** [comment]
We get too many questions from either new developers orply developers who haven't updated the project n a while, asking why a class is missing when they try to compile, so I'm looking for an automatic way to deal with it as part of the import itself.

**Comment by nskvortsov** [comment]
related discussion for eclipse: https://github.com/eclipse/buildship/issues/265

**Comment by nskvortsov** [comment]
proposed syntax:

    import org.jetbrains.gradle.ext.*
    idea {
      project.settings {
        taskTriggers {
          afterSync tasks.getByName('projects'), tasks.getByName('tasks')
        }
      }
    }

Tasks passed to `afterSync` will be called immediately after first import and after each following sync. Generated sources will be detected and picked up by Idea

**Comment by trejkaz** [comment]
Could also have shorthand:

```
import org.jetbrains.gradle.ext.*
idea {
  project.settings {
    taskTriggers {
      afterSync 'someTask', ':submodule:someOtherTask'
    }
  }
}
```

**Comment by trejkaz** [comment]
The only supported syntax is awkward when the task is in a subproject.

        afterSync project(':submodule-name').getByName('generateGrammarSource')

A shorthand would have been nice, along the lines of how I can use shorthand to specify dependencies.

**Comment by trejkaz** [comment]
Trying to work around the ordering problem using the standard Gradle way of declaring "all tasks of a type, including the ones defined in the future":

      taskTriggers {
        afterSync project(':submodule').tasks.withType(AntlrTask)
      }

Gives:

    Could not find method afterSync() for arguments [org.gradle.api.internal.tasks.RealizableTaskCollection@76ac12de] on object of type org.jetbrains.gradle.ext.TaskTriggersConfig.

**Comment by trejkaz** [comment]
Shortest workaround I was able to find to work around the ordering issue:

```
gradle.taskGraph.whenReady {
  idea.project.settings.taskTriggers {
    afterSync project(':submodule').tasks.getByName('taskInSubmodule')
  }
}
```

But I still wish I could just write this:

```
idea.project.settings.taskTriggers {
  afterSync ':submodule:taskInSubmodule'
}
```

It would have even been fairly clean if IDEA just always ran a certain hard-coded task, and anything we wanted to be run could be added as a dependency to that task...
