### ISSUE TITLE
Support importing code style scheme (exported by IntelliJ)

### ISSUE THREAD

**Issue by ewirch** [JetBrains/gradle-idea-ext-plugin#60]
This is probably a simple change, but would instantly allow to control all Code Style settings.

Importing existing schemes should overwrite them.
Importing a scheme should also select it.

**Comment by nskvortsov** [comment]
did you consider using `.editorconfig` configuration file?

**Comment by ewirch** [comment]
Yes. Its too limited. Does not even support max. line lengths ("hard wrap at").

**Comment by bric3** [comment]
Agreed `.editorConfig` only allow to configure spacing stuff, and do not take into account all the options available in the IJ code style settings, like import order, or alinement of exception, methods, etc. While I get that porting all settings to this plugin can be tedious, I think this plugin could tell IJ to load a style scheme file.

**Comment by bric3** [comment]
This one maybe be a solution to #40

**Comment by bric3** [comment]
@ewirch @nskvortsov How can we contribute this ?

**Comment by ewirch** [comment]
What do you mean by "how"? Code it and create a pull request.

**Comment by bric3** [comment]
@eriwen The thing is how, is there any documentation material to understand how this plugin work and integrates with IJ. Also is there any setup to do, the editor shows compiler error in `RunConfigurations.groovy`, yet under the hood this seems to compile.
A contributing guide would be quite welcome ;)

**Comment by ewirch** [comment]
> A contributing guide would be quite welcome ;)

I guess so. I think for the author the project is too small to come up with a contribution guide.

**Comment by bric3** [comment]
This ticket can probably dropped as the new way appear to be `.editorConfig`, as mentioned in https://github.com/JetBrains/gradle-idea-ext-plugin/issues/40#issuecomment-500778801, see

    https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-69685
    https://blog.jetbrains.com/idea/2019/06/intellij-idea-2019-2-eap3-code-style-per-scope-refreshed-code-completion-popup-and-more/

**Comment by nskvortsov** [comment]
closing, as code style is fully configurable by `.editorconfig`
