### ISSUE TITLE
JUnit run configuration: packageName not working

### ISSUE THREAD

**Issue by snrostov** [JetBrains/gradle-idea-ext-plugin#62]
For example:

```
junit("[JPS] All IDEA Plugin Tests") {
    moduleName = "org.jetbrains.kotlin.idea.test"
    packageName = "org.jetbrains.kotlin.*"
    configureForKotlin()
}
```

In IDEA run configuration without any test kind is created.
Looks like typo in `com.intellij.execution.junit.JUnitRunConfigurationImporter#process`:  first we search `packageName`, but in when we are trying to find `package`.

**Comment by nskvortsov** [comment]
indeed (
