### ISSUE TITLE
Artifacts: support $USER_HOME$ in paths

### ISSUE THREAD

**Issue by snrostov** [JetBrains/gradle-idea-ext-plugin#65]
This is useful for refering to gradle chache, for example: `<element id="extracted-dir" path="$USER_HOME$/.gradle/caches/modules-2/files-2.1/net.rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/50b15724c82808c2b7fefd9b0b7c6dd977623f35/native-platform-freebsd-i386-libcpp-0.14.jar" path-in-jar="/" />`

**Comment by nskvortsov** [comment]
obsolete. artifact definitions should not be shared, but should be generated upon import
