### ISSUE TITLE
Test runner settings not synchronized between external settings and idea settings

### ISSUE THREAD

**Issue by DeveloperHacker** [JetBrains/gradle-idea-ext-plugin#67]
# Steps to reproduce
1. Create simple gradle project
1. Change test runner on platfrom in `Build, Execution, Deployment | Build Tools | Gradle | Runner`
1. Add runner settings to gradle build file:
```
import static org.jetbrains.gradle.ext.ActionDelegationConfig.TestRunner.*

idea.project.settings {
    delegateActions {
        delegateBuildRunToGradle = true
        testRunner = GRADLE
    }
}
```
1. Synchronize gradle project
1. Checks runner settings but gradle runner was changed and it works

**Comment by nskvortsov** [comment]
Can you reproduce it with v 0.5 + Idea 2019.1 Beta 3

**Comment by DeveloperHacker** [comment]
I was wrong, this is not a bug, because `idea-ext-plugin` changes runner settings per linked project which are in `Build, Execution, Deployment | Build Tools | Gradle`.
![image](https://user-images.githubusercontent.com/11194423/54524828-f450f300-4983-11e9-9803-d0c7a85361d6.png)
