### ISSUE TITLE
Support configuring compiler annotation processors

### ISSUE THREAD

**Issue by dansanduleac** [JetBrains/gradle-idea-ext-plugin#68]
## What happened

I can't use this plugin to configure annotation processors.
Gradle now has a [per-source-set annotation processors classpath](https://blog.gradle.org/incremental-compiler-avoidance#about-annotation-processors) since 4.6, which means it's extremely important that we can take this classpath and inject it into intellij, rather than conflating it with the PROVIDED scope, which is what currently happens.

## What did you want to happen

I'd like the plugin to provide the ability to:

1. Control production & test output directories, including what they are relative to
1. Create "annotation processors" configuration groups, and assign projects to them
1. Set the "processor path" directly from a configuration (something which should be default anyway with Gradle 4.6+'s `annotationProcessor` configurations) ~ as opposed to detecting automatically from project classpath

In the order of importance. 

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/222827/52523224-e4f4d080-2c86-11e9-8af6-8e2a3827f2ee.png">

**Comment by nskvortsov** [comment]
This is going to be implemented out of the box by IntelliJ IDEA 2019.3
for details see 
https://youtrack.jetbrains.com/issue/IDEA-132286
https://youtrack.jetbrains.com/issue/IDEA-187868

**Comment by dansanduleac** [comment]
Confirmed this works indeed in 193.4099!
