### ISSUE TITLE
Package prefix configuration does not work

### ISSUE THREAD

**Issue by elizarov** [JetBrains/gradle-idea-ext-plugin#70]
As explained on this wiki page: https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/DSL-spec-v.-0.5
I'm writing the following `build.gradle` file:

```
plugins {
    id("java")
    id("org.jetbrains.gradle.plugin.idea-ext") version "0.5"
}

repositories {
    mavenCentral()
}

sourceSets {
    main.java.srcDirs = ["src"]
}

idea {
    module {
        settings {
            packagePrefix["src"] = "org.example"
        }
    }
}
```

Running it with Gradle 5.2 (via Gradle Wrapper) and importing into IDEA 2018.3.4 produces no effect on package prefix.

**Comment by DeveloperHacker** [comment]
Settings of [package prefixes](https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/DSL-spec-v.-0.5#package-prefix-requires-idea-20191) (and some features from idea-ext-plugin:0.5) supproted only from IDEA 2019.1.
