### ISSUE TITLE
afterSync task is added multiple times in workspace.xml

### ISSUE THREAD

**Issue by guylabs** [JetBrains/gradle-idea-ext-plugin#73]
When configuring an `afterSync` task, it will be added multiple times to the following part in the `.idea/workspace.xml` file:

```
...
<component name="ExternalProjectsManager">
    <system id="GRADLE">
      <state>
        <task path="$PROJECT_DIR$">
          <activation>
            <after_sync>
              <task name="afterSyncTask" />
              <task name="afterSyncTask" />
              <task name="afterSyncTask" />
            </after_sync>
          </activation>
        </task>
...
```

I guess this is a bug and it should only be listed once.

**Comment by vrudas** [comment]
@guylabs can you please provide information about the used versions of 'gradle-idea-ext-plugin' and  'IDEA' ?

**Comment by guylabs** [comment]
I just double checked and this is solved now. We are now using IntelliJ IDEA `2019.2.4` and `0.6.1` of the plugin.
