### ISSUE TITLE
Add docs / support to set system properties / env var for run configurations

### ISSUE THREAD

**Issue by gavenkoa** [JetBrains/gradle-idea-ext-plugin#75]
I'd like to set environment variable or system property for run configuration, like:

    <configuration default="true" type="SpringBootApplicationConfigurationType" factoryName="Spring Boot">
      <envs>
        <env name="SPRING_PROFILES_ACTIVE" value="test,postgres" />
      </envs>
       ....
    </configuration>

or:

    <configuration default="true" type="JUnit" factoryName="JUnit">
      <option name="VM_PARAMETERS" value="-Dspring.profiles.active=test,oracle" />
       ....
    </configuration>

I need to inject environment variable or system property to all run configurations in order to alter Spring profiles globally and without specifying "RunManager".

I want to externalize profile settings to some optional .properties file and allow to reconfigure IDEA project via syncing Gradle project.

**Comment by nskvortsov** [comment]
the run configurations of `Application` type has `envs` property that contains map of environment variables.

```
  "MyApp"(Application) {                    
    mainClass = 'foo.App'
    moduleName = getProject().idea.module.name
    envs = ["SPRING_PROFILES_ACTIVE": "test,postgres" ]
  }
```

the `JUnit` and `TestNG` run configurations has `jvmArgs` property:

```
  "MyTest"(JUnit) {
    vmParameters = "-Dspring.profiles.active=test,oracle"
  }
```

please see the doc https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/DSL-spec-v.-0.1 for details

**Comment by gavenkoa** [comment]
I am able to create predefined configuration with:

```
plugins {
    id "org.jetbrains.gradle.plugin.idea-ext" version "0.10"
}
idea.project.settings {
    runConfigurations {
        "Template"(org.jetbrains.gradle.ext.Gradle) {
            envs = ["SPRING_PROFILE": "my"]
        }
    }
}
```

But it is impossible to alter "Templates".

Originally I wanted to update Gradle/JUnit templates because dynamically created configuration inherits values from corresponding "Template".
