### ISSUE TITLE
Configuring taskTriggers in Kotlin DSL

### ISSUE THREAD

**Issue by sschuberth** [JetBrains/gradle-idea-ext-plugin#76]
Do to a lack of examples (see issue #44) I'm out of ideas how to port

```
idea.project.settings {
    taskTriggers {
        afterSync tasks.getByName('generateVersionResource')
        beforeBuild tasks.getByName('generateVersionResource')
    }
}
```

from Groovy DSL to Kotlin DSL. So far I've tried:

```
idea {
    project {
        (this as ExtensionAware)
        configure<ProjectSettings> {
            (this as ExtensionAware)
            taskTriggers {
                afterSync tasks.getByName("generateVersionResource")
                beforeBuild tasks.getByName("generateVersionResource")
            }
        }
    }
}
```

But the IDE still marks `taskTriggers` (and also the top `idea`) in red, complaining about type mismatches.

**Comment by sschuberth** [comment]
I've now found [this example](https://github.com/gradle/kotlin-dsl/blob/16400b4dbc80148cb464f4e762f99549626cd6e6/build.gradle.kts#L117) and thus I'm using

```
idea {
    project {
        this as ExtensionAware
        configure<ProjectSettings> {
            this as ExtensionAware
            configure<TaskTriggersConfig> {
                afterSync(generateGrammarSource.get())
                beforeBuild(generateGrammarSource.get())
            }
        }
    }
}
```

but for me this results in

    null cannot be cast to non-null type org.gradle.api.plugins.ExtensionAware

**Comment by mkobit** [comment]
@sschuberth maybe you are trying to do it in a subproject? I'm not sure if some parts of the `idea` extension are only generated in the root project.

Also, related to `kotlin-dsl` support is https://github.com/JetBrains/gradle-idea-ext-plugin/issues/44

**Comment by sschuberth** [comment]
Indeed, I'm applying the plugin in a subproject. Because if I don't, any only apply it in the root project, then the top-level `idea` block is already marked in red by the IDE, saying:

> Expression 'idea' cannot be invoked as a function. The function 'invoke()' is not found

**Comment by sschuberth** [comment]
Also, I should say that I'm migrating from Groovy to Kotlin script, and the Groovy code works with applying the plugin in the root and using it in a subproject.

**Comment by sschuberth** [comment]
Based on the ideas from [this code](https://github.com/JetBrains/kotlin/blob/27fd64ed4276f907079f41920fda3c4a6d530b2a/buildSrc/src/main/kotlin/ideaExtKotlinDsl.kt) I was able to apply the `idea-ext` plugin in the root project and then configure a sub-project using

    val generateVersionResource by tasks.registering { /* ... */ }

    fun Project.idea(block: IdeaModel.() -> Unit) =
        (this as ExtensionAware).extensions.configure("idea", block)

    fun IdeaProject.settings(block: ProjectSettings.() -> Unit) =
        (this@settings as ExtensionAware).extensions.configure(block)

    fun ProjectSettings.taskTriggers(block: TaskTriggersConfig.() -> Unit) =
        (this@taskTriggers as ExtensionAware).extensions.configure("taskTriggers", block)

    rootProject.idea {
        project {
            settings {
                taskTriggers {
                    afterSync(generateVersionResource.get())
                    beforeBuild(generateVersionResource.get())
                }
            }
        }
    }

**Comment by bric3** [comment]
I'm trying to make this work with 1.1.9, and idea 2024.3, but the task never "activates".

The task is located in a sub-project which is configured this way :

```
    rootProject.idea {
        project {
            settings {
                taskTriggers {
                    afterSync(generatedVersionClass.get())
                }
            }
        }
    }
```

Is there a change somewhere to observe in the `.idea` folder ?

**Comment by bric3** [comment]
So it seems that using the full path works better

```
rootProject.idea {
    project {
        settings {
            taskTriggers {
                afterSync(":mockito-core:generateVersionClass")
            }
        }
    }
}

```
