### ISSUE TITLE
Get module name when creating run configurations

### ISSUE THREAD

**Issue by deepy** [JetBrains/gradle-idea-ext-plugin#81]
Extracting this from #10 
When creating run configurations the we need to specify the module name, but since the group modules setting might be different (or multiple modules somewhere in the tree might have the same name).

How do we make sure we generate the launcher with the correct module name?

**Comment by trejkaz** [comment]
Somewhat related to #80 also (two potential solutions to the same problem.)

**Comment by deepy** [comment]
This is even trickier now with later versions of IDEA where separate modules per source set gives you names like `foo.main` (compared with the previous `foo_main`)

And since you can't turn off separate modules per source set any longer in 2019.2 this is becoming a PITA since some team members now have broken launchers

**Comment by nskvortsov** [comment]
support for module references added with following syntax:
```
runATest(JUnit) {
    moduleRef project(":"), sourceSets.test
    className = "my.app.Test1"
}
```

Only qualified module names import type is supported (module groups are deprecated)
