### ISSUE TITLE
Plugin Release Schedule

### ISSUE THREAD

**Issue by carterkozak** [JetBrains/gradle-idea-ext-plugin#90]
Quite a few changes have merged since the most recent release, is there any chance we could set up a release schedule to make these changes available to plugin consumers? Thanks!

**Comment by nskvortsov** [comment]
Current changes we be released in a scope of 1-2 weeks. But the real release schedule is yet TBD

**Comment by carterkozak** [comment]
Thanks for the information!

**Comment by nskvortsov** [comment]
After an internal discussions, we decided to align the release schedule with IDEA, so next large release (e.g., 1.0) of this plugin is expected to happen around release of IDEA 2020.3 
Smaller releases may more frequently
