### ISSUE TITLE
Dependency order

### ISSUE THREAD

**Issue by vitgorbunov** [JetBrains/gradle-idea-ext-plugin#93]
For some projects we need strict dependency order. I mean some dependencies must be on top of classpath for correct test running.

Is it possible to either always use dependency order how it's defined in gradle file or provide some way to change dependency order in generated project?

**Comment by nskvortsov** [comment]
IntelliJ IDEA is supposed to keep dependency order for compile/runtime classpath when importing Gradle project. 
If you observe different behaviour, please open issue in http:/youtrack.jetbrains.com attaching sample project for investingation.
