### ISSUE TITLE
Support enable/disable annotation processing

### ISSUE THREAD

**Issue by simomat** [JetBrains/gradle-idea-ext-plugin#94]
In our project, we use libraries that depend on java annotation processing. This can be enabled in idea settings, but we would like to make it enabled by default.

The ext plugin allready allows to modify compiler settings but managing annotation processing is not provided yet.

**Comment by nskvortsov** [comment]
@simomat if java annotation processing is configured properly in Gradle build (using `apt` plugin or `annotationProcessor` gradle configuration) it should be picked up automatically by IntelliJ IDEA 2019.3
Please try [latest 2019.3 Beta](https://www.jetbrains.com/idea/nextversion/) and see, if it works for you.

**Comment by simomat** [comment]
Yep, annotationProcessor and IDEA 2019.3 worked. Thanks!
